### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by heyskywalker** [mkearney/botornot#4]
Hi there. 

I am very keen on testing out your package on R, but I have been unable to install this package from the steps you have provided. I have tried this on multiple computers, to no avail. This is error message that I have been getting: 

`Downloading GitHub repo mkearney/botornot@master
from URL https://api.github.com/repos/mkearney/botornot/zipball/master
Installing botornot
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/8r/4b1mddcd5_d2_89fyb8x2_4r0000gn/T/RtmpPZMT3N/devtools8be10fdd7ef/mkearney-botornot-780fb5e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
* installing *source* package 'botornot' ...
** R
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'botornot_models'
** data
*** moving datasets to lazyload DB
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'botornot_model'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'botornot_model'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_usr'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_usr'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_all'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_all'
** preparing package for lazy loading
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Error : unable to load R code in package 'botornot'
ERROR: lazy loading failed for package 'botornot'
* removing '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/botornot'
Installation failed: Command failed (1)ed
by .GlobalEnv when processing object 'botornot_model'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'botornot_model'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_usr'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_usr'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_all'
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Warning: namespace 'botornot' is not available and has been replaced
by .GlobalEnv when processing object 'm_all'
** preparing package for lazy loading
Error in dataandme %>% mutate(created_at = utc_time(created_at), day = difftime(created_at,  : 
  could not find function "%>%"
Error : unable to load R code in package 'botornot'
ERROR: lazy loading failed for package 'botornot'
* removing '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/botornot'
Installation failed: Command failed (1)`

I hope you can help me out! Your project really excites me, and I can't wait to get started with this package. Thank you!

**Comment by shyamvalsan** [comment]
Yes, I see this error too on installing.

**Comment by mkearney** [comment]
Sorry, all. I'm in the middle of an overhaul. I've compiled a list of over 8,000 bots, and I've added a lot more features, so I should have a new model retrained and repackaged in here in the next few days. Although I think I added the dataandme.R file to the .Rbuildignore but it's entirely possible I forgot 👼

**Comment by shyamvalsan** [comment]
Neat, will wait for it. I've been compiling a huge list of twitter user ids to run botornot on, that's bound to take a few days anyway.

**Comment by mkearney** [comment]
I'm currently waiting on a dependency to be accepted by CRAN. Until then, you should be able to use this package by first installing the dependency from Github:

``` r
## install dep that's not yet on CRAN
devtools::install_github("mkearney/textfeatures")

## install botornot
devtools::install_github("mkearney/botornot")
```

You'll also need to make sure you are [authorized to interact with Twitter's APIs](http://rtweet.info/articles/auth.html).

**Comment by mkearney** [comment]
textfeatures is now on CRAN!

**Comment by atish111** [comment]
Hello,

I am trying to install the package but I am getting the following error:

Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/atish/AppData/Local/Temp/RtmpE1rH2W/file14906636558e/tweetbotornot_0.1.0.tar.gz’ had non-zero exit status
