### ISSUE TITLE
library(textfeatures)... dependency not on CRAN

### ISSUE THREAD

**Issue by rdrr1990** [mkearney/botornot#5]
Package looks great! When I attempt to install from github, it ultimately fails saying the dependency `textfeatures` is not available. This package isn't on CRAN and the [only github repo](https://github.com/trinker/textfeatures) I found is seriously incomplete (like no `NAMESPACE`). Is this dependency meant to be there and, if so, where can it be found?

**Comment by mkearney** [comment]
@rdrr1990 it's been submitted but got rejected first b/c name wasn't in title case and then second because of a false positive curl issue (which has got to be like a 1 in a thousand thing). It will hopefully be accepted by end of today. Until then you should be able to install from Github:

``` r
devtools::install_github("mkearney/textfeatures")
```

**Comment by mkearney** [comment]
@rdrr1990 and oh wow I didn't realize there was another omg by that name. The one I created should be functional!

**Comment by rdrr1990** [comment]
I'm disappointed in Google Chrome for not helping me find your other repo :) 

Works for fine now, thx!
