### ISSUE TITLE
textfeatures

### ISSUE THREAD

**Issue by thoughtfulbloke** [mkearney/botornot#6]
Just noting that for people not used to GitHub installs, as of 5 March the dependency on textfeatures is another mkearney GitHub repo that needs installing first. Maybe mentioning this in the ReadMe might be good guidance? I think it is likely to generate queries from people.

**Comment by mkearney** [comment]
Yep! This will hopefully be a non issue any hour now (its been submitted to CRAN), but for now you absolutely need to install this dep from Github https://github.com/mkearney/textfeatures

**Comment by mkearney** [comment]
The package is now on CRAN!
